/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppleAppSiteAssociationRouteImport } from './routes/apple-app-site-association'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UShareSlugRouteImport } from './routes/u/$shareSlug'

const AppleAppSiteAssociationRoute = AppleAppSiteAssociationRouteImport.update({
  id: '/apple-app-site-association',
  path: '/apple-app-site-association',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UShareSlugRoute = UShareSlugRouteImport.update({
  id: '/u/$shareSlug',
  path: '/u/$shareSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/apple-app-site-association': typeof AppleAppSiteAssociationRoute
  '/u/$shareSlug': typeof UShareSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/apple-app-site-association': typeof AppleAppSiteAssociationRoute
  '/u/$shareSlug': typeof UShareSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/apple-app-site-association': typeof AppleAppSiteAssociationRoute
  '/u/$shareSlug': typeof UShareSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$' | '/apple-app-site-association' | '/u/$shareSlug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$' | '/apple-app-site-association' | '/u/$shareSlug'
  id: '__root__' | '/' | '/$' | '/apple-app-site-association' | '/u/$shareSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AppleAppSiteAssociationRoute: typeof AppleAppSiteAssociationRoute
  UShareSlugRoute: typeof UShareSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/apple-app-site-association': {
      id: '/apple-app-site-association'
      path: '/apple-app-site-association'
      fullPath: '/apple-app-site-association'
      preLoaderRoute: typeof AppleAppSiteAssociationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$shareSlug': {
      id: '/u/$shareSlug'
      path: '/u/$shareSlug'
      fullPath: '/u/$shareSlug'
      preLoaderRoute: typeof UShareSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AppleAppSiteAssociationRoute: AppleAppSiteAssociationRoute,
  UShareSlugRoute: UShareSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
